#!/bin/bash
# example file to be used with --hookdir
#
# try to install the resulting debs.

echo "Trying to install resulting packages and test upgrades"
set -ex


PKGNAMES=$(cd /tmp/buildd && ls -1 *.deb | sed 's/_.*$//' )

echo -e "\ninstall-remove check\n"
dpkg -i /tmp/buildd/*.deb
dpkg --remove $PKGNAMES

echo -e "\ninstall-purge check\n"
dpkg -i /tmp/buildd/*.deb
dpkg --purge $PKGNAMES

echo -e "\nupgrade-remove check\n"
apt-get install -y --force-yes  $PKGNAMES || true
dpkg -i /tmp/buildd/*.deb
dpkg --remove $PKGNAMES

echo -e "\nupgrade-purge check\n"
apt-get install -y --force-yes $PKGNAMES || true
dpkg -i /tmp/buildd/*.deb
dpkg --purge $PKGNAMES

echo -e "\n"
